### ISSUE TITLE
may need to remove link to terms & units app

### ISSUE THREAD

**Issue by chrlaney** [cklunch/NEON-R-skills#2]
For security and for preserving active hours on your account, we may need to remove this link: https://cklunch.shinyapps.io/terms_app/. I haven't done a lot of reading about this yet, but any database exposed via a shiny app (or other online app) can be vulnerable to hacks.

**Comment by cklunch** [comment]
Thanks, good thought. I took it out in the pull request I just sent Leah, but it says there are merge conflicts...

**Comment by chrlaney** [comment]
Merge conflicts have been resolved; my edits have also reappeared - yay!
